name: Get SHA1

on: [workflow_dispatch]

jobs:
  get-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SHA1 Report
        run: |
          if [ -d "android" ]; then
            cd android
          fi
          if [ -f "gradlew" ]; then
            chmod +x gradlew
            ./gradlew signingReport
          else
            echo "لم يتم العثور على ملف gradlew في مشروعك. يرجى التأكد من وجود مجلد android."
            exit 1
          fi
