name: Get SHA1

on: [workflow_dispatch]

jobs:
  get-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradlew Executable & Run SHA1 Report
        run: |
          cd android
          chmod +x gradlew
          ./gradlew signingReport --continue
